// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB91fZg0gBmN1ReBvC27Uu_bYIimG_vP0Y',
    appId: '1:915300545667:web:1faacc0a6f8560a6a597b6',
    messagingSenderId: '915300545667',
    projectId: 'checklist-3f709',
    authDomain: 'checklist-3f709.firebaseapp.com',
    storageBucket: 'checklist-3f709.appspot.com',
    measurementId: 'G-M0ZKMT77V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdLtub3mbHEGXdIltti5mZKsAnWn4O1U',
    appId: '1:915300545667:android:8c86ca9a12bd125da597b6',
    messagingSenderId: '915300545667',
    projectId: 'checklist-3f709',
    storageBucket: 'checklist-3f709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3jGA906ljeSUg66b7cuLrl0lpYsXpHvU',
    appId: '1:915300545667:ios:fad7cc030fc6c63ba597b6',
    messagingSenderId: '915300545667',
    projectId: 'checklist-3f709',
    storageBucket: 'checklist-3f709.appspot.com',
    iosClientId: '915300545667-3aehan0piitsi0oi05cf8eps87iqeevg.apps.googleusercontent.com',
    iosBundleId: 'com.example.checklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3jGA906ljeSUg66b7cuLrl0lpYsXpHvU',
    appId: '1:915300545667:ios:fad7cc030fc6c63ba597b6',
    messagingSenderId: '915300545667',
    projectId: 'checklist-3f709',
    storageBucket: 'checklist-3f709.appspot.com',
    iosClientId: '915300545667-3aehan0piitsi0oi05cf8eps87iqeevg.apps.googleusercontent.com',
    iosBundleId: 'com.example.checklist',
  );
}
